//
// Document ready

$(function () {
	$.each(items, function (index, item) {
		$("body").append("<p>" + item.getIndex() + "</p>");
		$("body").append("<p>" + item.getName() + "</p>");
		$("body").append("<p>" + item.getHex() + "</p>");
		$("body").append("<p>" + item.getBinary() + "</p>");
		$("body").append("<hr />");
	});
});

//
// Item prototype

var Item = function (index, name) {
	this.index = index;
	this.name = name;
};

Item.prototype.getIndex = function () {
	return this.index;
}

Item.prototype.getName = function() {
	return this.name;
};

Item.prototype.getHex = function () {
	return this.index.toString(16).toUpperCase();
};

Item.prototype.getBinary = function () {
	return this.index.toString(2);
};

var items = new Array(
	new Item(  0, "Deku Stick"),
	new Item(  1, "Deku Nut"),
	new Item(  2, "Bomb"),
	new Item(  3, "Fairy Bow"),
	new Item(  4, "Fire Arrow"),
	new Item(  5, "Din's Fire"),
	new Item(  6, "Fairy Slingshot"),
	new Item(  7, "Fairy Ocarina"),
	new Item(  8, "Ocarina of Time"),
	new Item(  9, "Bombchu"),
	new Item( 10, "Hookshot"),
	new Item( 11, "Longshot"),
	new Item( 12, "Ice Arrow"),
	new Item( 13, "Farore's Wind"),
	new Item( 14, "Boomerang"),
	new Item( 15, "Lens of Truth"),
	new Item( 16, "Magic Beans"),
	new Item( 17, "Megaton Hammer"),
	new Item( 18, "Light Arrow"),
	new Item( 19, "Nayru's Love"),
	new Item( 20, "Empty Bottle"),
	new Item( 21, "Red Potion"),
	new Item( 22, "Green Potion"),
	new Item( 23, "Blue Potion"),
	new Item( 24, "Bottled Fairy"),
	new Item( 25, "Fish"),
	new Item( 26, "Lon Lon Milk"),
	new Item( 27, "Letter"),
	new Item( 28, "Blue Fire"),
	new Item( 29, "Bug"),
	new Item( 30, "Big Poe"),
	new Item( 31, "Lon Lon Milk (Half)"),
	new Item( 32, "Poe"),
	new Item( 33, "Weird Egg"),
	new Item( 34, "Chicken"),
	new Item( 35, "Zelda's Letter"),
	new Item( 36, "Keaton Mask"),
	new Item( 37, "Skull Mask"),
	new Item( 38, "Spooky Mask"),
	new Item( 39, "Bunny Hood"),
	new Item( 40, "Goron Mask"),
	new Item( 41, "Zora Mask"),
	new Item( 42, "Gerudo Mask"),
	new Item( 43, "Mask of Truth"),
	new Item( 44, "SOLD OUT"),
	new Item( 45, "Pocket Egg"),
	new Item( 46, "Pocket Cucco"),
	new Item( 47, "Cojiro"),
	new Item( 48, "Odd Mushroom"),
	new Item( 49, "Odd Potion"),
	new Item( 50, "Poacher's Saw"),
	new Item( 51, "Goron's Sword (Broken)"),
	new Item( 52, "Prescription"),
	new Item( 53, "Eye Ball Frog"),
	new Item( 54, "Eye Drops"),
	new Item( 55, "Claim Check"),
	new Item( 56, "Fairy Bow + Fire Arrow"),
	new Item( 57, "Fairy Bow + Ice Arrow"),
	new Item( 58, "Fairy Bow + Light Arrow"),
	new Item( 59, "Kokiri Sword"),
	new Item( 60, "Master Sword"),
	new Item( 61, "Biggoron Sword / Giant's Knife"),
	new Item( 62, "Deku Shield"),
	new Item( 63, "Hylian Shield"),
	new Item( 64, "Mirror Shield"),
	new Item( 65, "Kokiri Tunic"),
	new Item( 66, "Goron Tunic"),
	new Item( 67, "Zora Tunic"),
	new Item( 68, "Kokiri Boots"),
	new Item( 69, "Iron Boots"),
	new Item( 70, "Hover Boots"),
	new Item( 71, "Bullet Bag (30)"),
	new Item( 72, "Bullet Bag (40)"),
	new Item( 73, "Bullet Bag (50)"),
	new Item( 74, "Quiver (30)"),
	new Item( 75, "Quiver (40)"),
	new Item( 76, "Quiver (50)"),
	new Item( 77, "Bomb Bag (20)"),
	new Item( 78, "Bomb Bag (30)"),
	new Item( 79, "Bomb Bag (40)"),
	new Item( 80, "Goron's Bracelet"),
	new Item( 81, "Silver Gauntlets"),
	new Item( 82, "Golden Gauntlets"),
	new Item( 83, "Silver Scale"),
	new Item( 84, "Golden Scale"),
	new Item( 85, "Giant's Knife (Broken)"),
	new Item( 86, "Adult's Wallet"),
	new Item( 87, "Giant's Wallet"),
	new Item( 88, "Deku Seeds"),
	new Item( 89, "Fishing Rod"),
	new Item( 90, "Minuet of Forest"),
	new Item( 91, "Bolero of Fire"),
	new Item( 92, "Serenade of Water"),
	new Item( 93, "Requiem of Spirit"),
	new Item( 94, "Nocturn of Shadow"),
	new Item( 95, "Prelude of Light"),
	new Item( 96, "Zelda's Lullaby"),
	new Item( 97, "Epona's Song"),
	new Item( 98, "Saria's Song"),
	new Item( 99, "Sun's Song"),
	new Item(100, "Song of Time"),
	new Item(101, "Song of Storms"),
	new Item(102, "Forest Medallion"),
	new Item(103, "Fire Medallion"),
	new Item(104, "Water Medallion"),
	new Item(105, "Spirit Medallion"),
	new Item(106, "Shadow Medallion"),
	new Item(107, "Light Medallion"),
	new Item(108, "Kokiri Emerald"),
	new Item(109, "Goron's Ruby"),
	new Item(110, "Zora's Sapphire"),
	new Item(111, "Stone of Agony"),
	new Item(112, "Gerudo Card"),
	new Item(113, "Gold Skulltula"),
	new Item(114, "Piece of Heart")
);

var inventory = new Array(
	"Deku Stick",
	"Deku Nut",
	"Bombs",
	"Fairy Bow",
	"Fire Arrow",
	"Din's Fire",
	"Fairy Slingshot",
	"Fairy Ocarina/Ocarina of Time",
	"Bombchus",
	"Hookshot/Longshot",
	"Ice Arrow",
	"Farore's Wind",
	"Boomerang",
	"Lens of Truth",
	"Magic Beans",
	"Megaton Hammer",
	"Light Arrow",
	"Nayru's Love",
	"Bottle #1",
	"Bottle #2",
	"Bottle #3",
	"Bottle #4",
	"Adult Trade Item",
	"Child Trade Item",
	"Deku Stick #",
	"Deku Nut #",
	"Bombs #",
	"Fairy Bow #",
	"Fire Arrow #",
	"Din's Fire #",
	"Fairy Slingshot #",
	"Fairy Ocarina/Ocarina of Time #",
	"Bombchus #",
	"Hookshot/Longshot #",
	"Ice Arrow #",
	"Farore's Wind #",
	"Boomerang #",
	"Lens of Truth #",
	"Magic Beans #",
	"Magic Beans Popularity",
	"Tunics/Boots",
	"Swords/Shields",
	"?",
	"?",
	"?",
	"Nut/Stick Capacity + Bullet Bag",
	"Bullet Bag + Wallet Size + Dive Meter + Strength",
	"Strength + Bomb Bag + Quiver",
	"Heart Pieces",
	"Song of Time/Storms + Kokiri Emerald + Goron Ruby + Zora Sapphire + Stone of Agony + Gerudo Card + Skulltulas",
	"Serenade + Requiem + Nocturn + Prelude + ZL + Epona's + Saria's + Sun's",
	"Forest M + Fire M + Water M + Spirit M + Shadow M + Light M + Minuet + Bolero",
	"Deku Tree BK + Compass + Map",
	"Dodongo's Cavern BK + Compass + Map",
	"Jabu Jabu's Belly BK + Compass + Map",
	"Forest BK + Compass + Map",
	"Fire BK + Compass + Map",
	"Water BK + Compass + Map",
	"Spirit BK + Compass + Map",
	"Shadow BK + Compass + Map",
	"BotW",
	"Ice Cavern",
	"Ganon's Tower",
	"GtG",
	"Thieve's Hideout",
	"Inside Ganon's Tower",
	"Tower Collapse Interior",
	"Tower Collapse Interior Exit",
	"Treasure Chest Shop",
	"Deku Boss Room",
	"Dodongo's Boss Room",
	"Jabu's Boss Room",
	"Deku Tree Small Keys",
	"Dodongo's Cavern Small Keys",
	"Jabu Jabu's Belly Small Keys",
	"Forest Temple Small Keys",
	"Fire Temple Small Keys",
	"Water Temple Small Keys",
	"Spirit Temple Small Keys",
	"Shadow Temple Small Keys",
	"BotW Small Keys",
	"Ice Cavern Small Keys",
	"Ganon's Tower Small Keys",
	"Gerudo Training Ground Small Keys",
	"Gerudo Fortress Small Keys"
);